#!/bin/bash
# Prevent Veeam backups when connected to FortiClient VPN
# Re-enable traffic when VPN disconnects

VEEAM_REPO_IPS=("<SERVER_IP_ADDRESS>")
PF_ANCHOR="/etc/pf.anchors/block-veeam"
PF_CONF="/etc/pf.conf"
LOG_FILE="/var/log/prevent-vpn-backup.log"

log() { echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$LOG_FILE"; }

# Detect active Forticlient VPN interface (IPv4 only)

is_vpn_connected() {
    vpn_ip=$(ifconfig | awk '
        /^utun/ { iface=$1 }
        /inet / && iface ~ /^utun/ {
            if ($2 != "127.0.0.1") {
                print $2
                exit
            }
        }')
    [[ -n "$vpn_ip" ]]
}

# Enable firewall blocking rules when VPN is connected

enable_block() {
    {
        echo "# Auto-generated by prevent-vpn-backup.sh"
        for ip in "${VEEAM_REPO_IPS[@]}"; do
            echo "block drop from any to $ip"
        done
    } | tee "$PF_ANCHOR" >/dev/null

    if ! grep -q 'anchor "block-veeam"' "$PF_CONF"; then
        echo 'anchor "block-veeam"' | tee -a "$PF_CONF" >/dev/null
        echo 'load anchor "block-veeam" from "/etc/pf.anchors/block-veeam"' | tee -a "$PF_CONF" >/dev/null
    fi

    pfctl -f "$PF_CONF" >/dev/null 2>&1
    pfctl -e 2>/dev/null
    log "VPN detected — blocked Veeam traffic."
}

# Disable firewall blocking rules (VPN disconnected)

disable_block() {
    if grep -q 'anchor "block-veeam"' "$PF_CONF"; then
        # Remove anchor lines from pf.conf
        sed -i.bak '/anchor "block-veeam"/d' "$PF_CONF"
        sed -i.bak '/load anchor "block-veeam" from "\/etc\/pf.anchors\/block-veeam"/d' "$PF_CONF"
    fi

    # Remove anchor file

    [ -f "$PF_ANCHOR" ] && rm -f "$PF_ANCHOR"

    # Reload firewall

    pfctl -f "$PF_CONF" >/dev/null 2>&1
    log "VPN disconnected - unblocked Veeam traffic."
}

# Main function

if is_vpn_connected; then
    enable_block
else
    disable_block
fi

exit 0
